version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13.1
    commands:
      - python3 -m venv venv
      - source venv/bin/activate  # Activate the virtual environment
  build:
    commands:
      - pip install -r requirements.txt  # Install dependencies

      # Zip the Lambda function, excluding non-essential files
      - zip -r lambda_function.zip . -x ".gitignore" -x "*.yml" -x "*.md" -x "*.txt"

  post-build:
    commands:
      - echo "Build Complete"
artifacts:
  files:
    - lambda_function.zip
